services:
  nginx:
    build:
      context: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html/static
    networks:
      - net
    depends_on:
      - db
      - app
  db:
    image: postgres:16.0
    volumes:
      - pd_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - net
  app:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - DB_HOST=db
      - LOG_LEVEL=debug
    depends_on:
      - db
    networks:
      - net

networks:
  net:

volumes:
  pd_data:
  static_files: { }