services:
  db:
    image: postgres
    volumes:
      - pd_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
  app:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - DB_HOST=db
      - LOG_LEVEL=debug
    depends_on:
      - db

volumes:
  pd_data: