create table ARTICLES
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    headline varchar(256) not null,
    content text not null,
    pub_date TIMESTAMP
);

create Table UserRequests
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(256) not NULL,
    message TEXT NOT NULL,
    pub_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);